import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Login</Link>
        </li>
        <li>
          <Link to="/selectwallet">SelectWallet</Link>
        </li>
        <li>
          <Link to="/smartcontract">SmartContract</Link>
        </li>
        <li>
          <Link to="/walletcreationone">WalletCreationOne</Link>
        </li>
        <li>
          <Link to="/label7ten">Label7Ten</Link>
        </li>
        <li>
          <Link to="/masterwalleterror">MasterWalletError</Link>
        </li>
        <li>
          <Link to="/summary">Summary</Link>
        </li>
        <li>
          <Link to="/projectcostinsert">ProjectCostInsert</Link>
        </li>
        <li>
          <Link to="/downloadcompleted">DownloadCompleted</Link>
        </li>
        <li>
          <Link to="/loading">Loading</Link>
        </li>
        <li>
          <Link to="/walletcreationten">WalletCreationTen</Link>
        </li>
        <li>
          <Link to="/label1six">Label1Six</Link>
        </li>
        <li>
          <Link to="/summaryareyousure">SummaryAreyousure</Link>
        </li>
        <li>
          <Link to="/projectcostinserting">ProjectCostInserting</Link>
        </li>
        <li>
          <Link to="/selectwalletphantom">SelectWalletPhantom</Link>
        </li>
        <li>
          <Link to="/masterwalletcontinue">MasterWalletContinue</Link>
        </li>
        <li>
          <Link to="/smartcontract1selected">SmartContract1Selected</Link>
        </li>
        <li>
          <Link to="/summarysuccess">SummarySuccess</Link>
        </li>
        <li>
          <Link to="/projectcostsufficientbalance">
            ProjectCostSufficientBalance
          </Link>
        </li>
        <li>
          <Link to="/smartcontract2selected">SmartContract2Selected</Link>
        </li>
        <li>
          <Link to="/selectwalletsolflare">SelectWalletSolflare</Link>
        </li>
        <li>
          <Link to="/summaryerror">SummaryError</Link>
        </li>
        <li>
          <Link to="/projectcostinsufficientbalance">
            ProjectCostInsufficientBalance
          </Link>
        </li>
        <li>
          <Link to="/smartcontractselect">SmartContractSelect</Link>
        </li>
        <li>
          <Link to="/loginresponsive">LoginResponsive</Link>
        </li>
        <li>
          <Link to="/selectwallet1">SelectWallet1</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
